#!/bin/zsh

# variables
DIR="`git rev-parse --show-toplevel`/todo"
if [ ! -d "$DIR" ]; then
	DIR="`git rev-parse --show-toplevel`"
fi
VENV_DIR="$DIR/.venv"
BIN_DIR="$HOME/.local/bin"
TODO_BIN="$BIN_DIR/todo"

# usage
USAGE="./install.sh [-h|--help] [-v|--verbose]
 -> [-h|--help]: print usage
 -> [-v|--verbose]: verbose mode
"

# arguments
# https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash
VERBOSE=false

# save args in variable
args="$@"

POSITIONAL=()
while [[ $# -gt 0 ]]
do
	key="$1"

	case $key in
		-v|--verbose)
		VERBOSE=true
		shift # past argument
		;;
		-h|--help)
		echo "$USAGE"
		exit 0
		;;
		*)    # unknown option
		POSITIONAL+=("$1") # save it in an array for later
		shift # past argument
		;;
	esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

source $DIR/../scripts/utils.sh $args

if $VERBOSE; then
	verbose='cat'
else
	verbose='> /dev/null'
fi

# init timrc
printf "${TITLE_S}init timrc todo${TITLE_E}"
init_timrc
set_timrc_var "TIMRC_TODO" "$DIR"

# install python venv
# built from sys.base_prefix, so an activated project venv is never used as the interpreter base
if [ ! -d "$VENV_DIR" ]; then
	printf "${TITLE_S}create todo venv${TITLE_E}"
	BASE_PYTHON="$(python3 -c 'import os, sys; print(os.path.join(sys.base_prefix, "bin", f"python{sys.version_info.major}.{sys.version_info.minor}"))')"
	if [ ! -x "$BASE_PYTHON" ]; then
		BASE_PYTHON="$(command -v python3)"
	fi
	printf "${ADD_S}base interpreter: $BASE_PYTHON${ADD_E}" | eval $verbose
	"$BASE_PYTHON" -m venv "$VENV_DIR" | eval $verbose
fi

# install python dependencies
printf "${TITLE_S}install todo dependencies${TITLE_E}"
"$VENV_DIR/bin/pip" install -q -r "$DIR/requirements.txt" | eval $verbose

# install todo launcher
printf "${TITLE_S}install todo launcher${TITLE_E}"
mkdir -p "$BIN_DIR"
cat > "$TODO_BIN" << EOF
#!/bin/sh
# generated by $DIR/install_todo.sh, do not edit by hand
export PYTHONPATH="$DIR:\$PYTHONPATH"
exec "$VENV_DIR/bin/python" -m todotxt "\$@"
EOF
chmod +x "$TODO_BIN"
